"""add audio briefings

Revision ID: 56b54dded140
Revises: b6373a3d72c8
Create Date: 2026-09-16 13:08:23.314389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b54dded140'
down_revision: Union[str, Sequence[str], None] = 'b6373a3d72c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('briefing_date', sa.Date(), nullable=False),
    sa.Column('length_minutes', sa.Integer(), nullable=False),
    sa.Column('script', sa.String(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('briefing_date', 'length_minutes')
    )
    op.create_index(op.f('ix_audio_briefings_briefing_date'), 'audio_briefings', ['briefing_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_briefings_briefing_date'), table_name='audio_briefings')
    op.drop_table('audio_briefings')
    # ### end Alembic commands ###
