"""add story_clusters and cluster fields

Revision ID: 6155dede75c3
Revises: 05cd4e76ed10
Create Date: 2026-09-15 13:51:10.687981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6155dede75c3'
down_revision: Union[str, Sequence[str], None] = '05cd4e76ed10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_clusters_cluster_date'), 'story_clusters', ['cluster_date'], unique=False)
    op.add_column('raw_articles', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.add_column('raw_articles', sa.Column('cluster_similarity', sa.Float(), nullable=True))
    op.create_foreign_key(
        'fk_raw_articles_cluster_id', 'raw_articles', 'story_clusters', ['cluster_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_raw_articles_cluster_id', 'raw_articles', type_='foreignkey')
    op.drop_column('raw_articles', 'cluster_similarity')
    op.drop_column('raw_articles', 'cluster_id')
    op.drop_index(op.f('ix_story_clusters_cluster_date'), table_name='story_clusters')
    op.drop_table('story_clusters')
    # ### end Alembic commands ###
