"""add story subcategory

Revision ID: 9cae518c5914
Revises: d3b89f8c78b5
Create Date: 2026-09-15 22:37:46.306509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cae518c5914'
down_revision: Union[str, Sequence[str], None] = 'd3b89f8c78b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('subcategory', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'subcategory')
    # ### end Alembic commands ###
