"""add stories, story_sources, daily_digests

Revision ID: d3b89f8c78b5
Revises: 6155dede75c3
Create Date: 2026-09-15 20:54:54.965135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3b89f8c78b5'
down_revision: Union[str, Sequence[str], None] = '6155dede75c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_digests',
    sa.Column('digest_date', sa.Date(), nullable=False),
    sa.Column('bullets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('digest_date')
    )
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('why_it_matters', sa.String(), nullable=False),
    sa.Column('what_to_watch', sa.String(), nullable=False),
    sa.Column('key_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('perspectives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['story_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id')
    )
    op.create_index(op.f('ix_stories_date'), 'stories', ['date'], unique=False)
    op.create_table('story_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_sources')
    op.drop_index(op.f('ix_stories_date'), table_name='stories')
    op.drop_table('stories')
    op.drop_table('daily_digests')
    # ### end Alembic commands ###
